"""Holonomy diagnostics and the Helmholtz decomposition.

These two operators carry the conceptual weight of the fluid layer:

- The **Helmholtz decomposition** splits any force field into a gradient
  (appropriative / dominance-hierarchy) part and a solenoidal (generative) part --
  the unique split of Remark 2.1.

- The **holonomy** ``hol(gamma) = oint u . dl`` (eq. 5) is the net value generated by
  traversing a closed relational loop once. By Proposition 2.1 it is blind to the
  gradient part of the flow and sourced only by circulation.
"""

from __future__ import annotations

import numpy as np

from .grid import Grid2D


def helmholtz_decomposition(
    grid: Grid2D, fx: np.ndarray, fy: np.ndarray
) -> tuple[tuple[np.ndarray, np.ndarray], tuple[np.ndarray, np.ndarray]]:
    """Split a vector field ``f`` into gradient and solenoidal parts.

    Returns ``(grad_part, sol_part)`` with ``f = grad_part + sol_part`` where
    ``grad_part = grad(phi)`` is curl-free (the appropriative drive) and
    ``sol_part`` is divergence-free (the generative, circulation-bearing drive).

    The split is unique on a periodic domain once the mean mode is fixed. The
    spatially-uniform component of ``f`` is both curl- and divergence-free; we
    attach it to the solenoidal part by convention so that ``grad_part`` is a pure
    gradient with zero mean.
    """
    phi = grid.solve_poisson(grid.div(fx, fy))
    gx, gy = grid.grad(phi)
    sx, sy = fx - gx, fy - gy
    return (gx, gy), (sx, sy)


def circulation_loop(
    grid: Grid2D, ux: np.ndarray, uy: np.ndarray, i0: int, i1: int, j0: int, j1: int
) -> float:
    """Holonomy ``oint u . dl`` around the axis-aligned rectangular loop.

    The loop encloses grid indices ``[i0, i1] x [j0, j1]`` and is traversed
    counter-clockwise. This is the direct line-integral form of eq. (5); it should
    agree with :func:`circulation_stokes` (the area integral of vorticity) to
    discretization error, which is the discrete content of Stokes' theorem.
    """
    dx, dy = grid.dx, grid.dy
    # Bottom edge (j = j0), x increasing: +ux
    bottom = np.sum(ux[i0:i1, j0]) * dx
    # Right edge (i = i1), y increasing: +uy
    right = np.sum(uy[i1, j0:j1]) * dy
    # Top edge (j = j1), x decreasing: -ux
    top = -np.sum(ux[i0:i1, j1]) * dx
    # Left edge (i = i0), y decreasing: -uy
    left = -np.sum(uy[i0, j0:j1]) * dy
    return float(bottom + right + top + left)


def circulation_stokes(
    grid: Grid2D, omega: np.ndarray, i0: int, i1: int, j0: int, j1: int
) -> float:
    """Circulation via Stokes' theorem: ``integral of omega dA`` over the rectangle.

    Provided as an independent cross-check on :func:`circulation_loop`.
    """
    return float(np.sum(omega[i0:i1, j0:j1]) * grid.cell_area())


def holonomy_sign(value: float, tol: float = 1e-9) -> int:
    """Report only the *sign* of a holonomy: +1, 0, or -1.

    The model forbids reporting an absolute holonomy magnitude as a result
    (paper §4.5): magnitude is defined only relative to an arbitrary connection,
    while the sign -- generative (+), appropriative (0), dominative (-) -- is
    scale-invariant and is what the good/bad criterion rests on.
    """
    if value > tol:
        return 1
    if value < -tol:
        return -1
    return 0
